"""Données du cabinet de démonstration (fictives).

Sources : « Profils Cabinet » (32 profils), « Dossiers du cabinet » (32 dossiers), « Critères d'attribution ».
Les informations absentes des documents ont été complétées de façon cohérente :
- profils : sous-spécialités, domaines secondaires (pour que chaque dossier ait des candidats), secteurs, pays,
  systèmes juridiques, préférences, expérience contentieuse / transactionnelle / internationale ;
- dossiers : client (secteur, langue, pays), échéance, charge estimée, équipe ; la colonne « Rang » du tableau
  est utilisée comme priorité ; les 3 dossiers du tableau sans description en ont reçu une, et les 3 descriptions
  en double (Horizon Payments, BrightWave, Commission européenne / télécoms) ont été écartées.
"""
from app.models import Role

# --------------------------------------------------------------------------- domaines et sous-spécialités
DOMAINS = {
    "M&A et private equity": ["Acquisitions de sociétés", "Opérations transfrontalières",
                              "Contrôle des investissements étrangers", "Fusions", "Fonds d'investissement",
                              "Due diligence"],
    "Droit des sociétés": ["Restructurations de groupe", "Joint-ventures et implantation internationale",
                           "Droit OHADA", "Audit contractuel"],
    "Restructuring et financement": ["Procédures collectives", "Restructuration de dette",
                                     "Financement de projets et sûretés", "Réglementation bancaire"],
    "Pénal des affaires": ["Corruption et enquêtes internes", "Fraude et abus de biens sociaux"],
    "Compliance": ["Anticorruption (Sapin II)", "RGPD et IA", "Droit de la concurrence"],
    "Contentieux des affaires": ["Contentieux contractuel", "Rupture brutale et distribution", "Recouvrement",
                                 "Contentieux international et arbitrage", "Assurances"],
    "Droit social": ["Licenciements économiques (PSE)", "Cadres dirigeants"],
    "Propriété intellectuelle et numérique": ["Brevets", "Marques", "Contrats IT et SaaS", "Bases de données"],
    "Droit fiscal": ["Prix de transfert et contrôle fiscal"],
    "Droit public des affaires": ["Commande publique"],
    "Droit immobilier": ["Baux commerciaux"],
}

M_A, CORP, RESTR = "M&A et private equity", "Droit des sociétés", "Restructuring et financement"
PENAL, COMPL, CONT = "Pénal des affaires", "Compliance", "Contentieux des affaires"
SOCIAL, PI, FISC = "Droit social", "Propriété intellectuelle et numérique", "Droit fiscal"
PUBLIC, IMMO = "Droit public des affaires", "Droit immobilier"

RATES = {Role.PARTNER: 500, Role.SENIOR: 320, Role.ASSOCIATE: 250, Role.JUNIOR: 180,
         Role.INTERN: 80}

# « exemple » à la connexion ouvre un vrai profil, pour aller vite en démo
EXAMPLE_ALIASES = {Role.PARTNER: "Jean Moreau", Role.ASSOCIATE: "Léa Garnier", Role.INTERN: "Hugo Lambert"}

# --------------------------------------------------------------------------- profils
# domains : {domaine: (niveau 1-3, dossiers traités)} ; subs : {sous-spécialité: (niveau, dossiers traités)}
# lit / trans / intl : expérience contentieuse, transactionnelle (0-3), internationale (0-2)
PEOPLE = [
    # ----- Associés
    dict(name="Jean Moreau", role=Role.PARTNER, age=48, years=15, specialty="M&A / Private Equity",
         langs="Français C2, Anglais C2, Espagnol B2",
         domains={M_A: (3, 120), CORP: (2, 40)},
         subs={"Acquisitions de sociétés": (3, 60), "Fonds d'investissement": (3, 25), "Opérations transfrontalières": (3, 30)},
         sectors="Banque et finance, Énergie, Technologies", countries="France, Royaume-Uni, Espagne, États-Unis",
         legal="Droit français, Common law, Droit de l'UE", prefs="négociation", lit=1, trans=3, intl=2),
    dict(name="Claire Delattre", role=Role.PARTNER, age=46, years=12, specialty="Pénal des affaires / Compliance",
         langs="Français C2, Anglais C1, Italien B2",
         domains={PENAL: (3, 90), COMPL: (3, 60)},
         subs={"Corruption et enquêtes internes": (3, 40), "Anticorruption (Sapin II)": (3, 30)},
         sectors="BTP, Industrie, Énergie", countries="France, Italie", legal="Droit français, Droit de l'UE",
         prefs="contentieux, négociation", lit=3, trans=1, intl=1),
    dict(name="Pierre Richard", role=Role.PARTNER, age=40, years=8, specialty="M&A",
         langs="Français C2, Anglais C2", domains={M_A: (3, 70), CORP: (2, 25)},
         subs={"Acquisitions de sociétés": (3, 35), "Fusions": (3, 15), "Opérations transfrontalières": (2, 12)},
         sectors="Technologies, Industrie, Matériaux de construction", countries="France, États-Unis, Royaume-Uni",
         legal="Droit français, Common law", prefs="négociation, rédaction", trans=3, intl=2),
    dict(name="Sarah Cohen", role=Role.PARTNER, age=39, years=8, specialty="Pénal des affaires",
         langs="Français C2, Anglais C1", domains={PENAL: (3, 55), COMPL: (2, 15)},
         subs={"Corruption et enquêtes internes": (3, 25), "Fraude et abus de biens sociaux": (3, 20)},
         sectors="BTP, Distribution / retail", prefs="contentieux", lit=3),
    dict(name="Nicolas Martin", role=Role.PARTNER, age=41, years=8, specialty="Contentieux commercial",
         langs="Français C2, Anglais B2", domains={CONT: (3, 80), PUBLIC: (2, 10), SOCIAL: (2, 12)},
         subs={"Contentieux contractuel": (3, 35), "Rupture brutale et distribution": (3, 20),
               "Contentieux international et arbitrage": (2, 10)},
         sectors="Industrie, Distribution / retail, BTP", countries="France, Espagne, Maroc",
         legal="Droit français, Droit de l'UE", prefs="contentieux", lit=3, intl=1),
    dict(name="Marie Lefèvre", role=Role.PARTNER, age=38, years=7, specialty="Compliance",
         langs="Français C2, Anglais C2", domains={COMPL: (3, 50), PENAL: (2, 10)},
         subs={"Anticorruption (Sapin II)": (3, 20), "RGPD et IA": (3, 18), "Droit de la concurrence": (2, 8)},
         sectors="Technologies, Sidérurgie, Distribution / retail", legal="Droit français, Droit de l'UE",
         prefs="recherche, négociation", lit=1, trans=1, intl=1),
    dict(name="Thomas Bernard", role=Role.PARTNER, age=38, years=7, specialty="Corporate",
         langs="Français C2, Anglais B2", domains={CORP: (3, 60), M_A: (2, 15), IMMO: (2, 8)},
         subs={"Restructurations de groupe": (3, 20), "Droit OHADA": (3, 12), "Joint-ventures et implantation internationale": (3, 10)},
         sectors="Mines, Industrie, Conseil", countries="France, Côte d'Ivoire, Sénégal, Maroc",
         legal="Droit français, Droit OHADA", prefs="rédaction, négociation", trans=3, intl=2),
    dict(name="Camille Dubois", role=Role.PARTNER, age=37, years=6, specialty="Private Equity",
         langs="Français C2, Anglais C2", domains={M_A: (3, 45), FISC: (2, 10)},
         subs={"Fonds d'investissement": (3, 25), "Contrôle des investissements étrangers": (2, 6)},
         sectors="Capital-investissement, Technologies, Énergie", countries="France, Luxembourg, Royaume-Uni",
         legal="Droit français, Droit de l'UE", prefs="négociation", trans=3, intl=1),
    dict(name="Julien Mercier", role=Role.PARTNER, age=42, years=8, specialty="Restructuring",
         langs="Français C2, Anglais B2", domains={RESTR: (3, 55), CORP: (2, 15)},
         subs={"Procédures collectives": (3, 25), "Restructuration de dette": (3, 20), "Financement de projets et sûretés": (2, 8)},
         sectors="Industrie, Chimie, Énergie", legal="Droit français, Droit OHADA", prefs="négociation",
         lit=2, trans=2, intl=1),
    # ----- Collaborateurs seniors
    dict(name="Léa Garnier", role=Role.SENIOR, age=34, years=6, specialty="M&A Tech",
         langs="Français C2, Anglais C2", domains={M_A: (3, 40), PI: (2, 12)},
         subs={"Acquisitions de sociétés": (3, 18), "Opérations transfrontalières": (3, 10), "Due diligence": (3, 20),
               "Fusions": (2, 5), "Contrôle des investissements étrangers": (2, 4),
               "Contrats IT et SaaS": (2, 8), "Bases de données": (2, 4)},
         types={"transactionnel": 30, "audit": 20, "acte": 15},
         sectors="Technologies, Banque et finance", countries="France, États-Unis, Royaume-Uni",
         legal="Droit français, Common law", prefs="négociation, rédaction", lit=1, trans=3, intl=2),
    dict(name="Arthur Simon", role=Role.SENIOR, age=33, years=5, specialty="Pénal des affaires",
         langs="Français C2, Anglais C1", domains={PENAL: (3, 30), COMPL: (2, 8)},
         subs={"Corruption et enquêtes internes": (3, 14), "Fraude et abus de biens sociaux": (3, 10),
               "Anticorruption (Sapin II)": (2, 6)},
         types={"contentieux": 20, "conseil": 10, "consultation": 12},
         sectors="BTP, Énergie", prefs="contentieux, recherche", lit=3, intl=1),
    dict(name="Hugo Blanc", role=Role.SENIOR, age=35, years=6, specialty="Contentieux commercial",
         langs="Français C2, Anglais B2", domains={CONT: (3, 45), PI: (2, 9), SOCIAL: (2, 5), RESTR: (1, 3)},
         subs={"Contentieux contractuel": (3, 20), "Rupture brutale et distribution": (3, 12), "Recouvrement": (3, 15),
               "Contentieux international et arbitrage": (2, 6), "Assurances": (2, 5), "Brevets": (2, 4),
               "Marques": (2, 5), "Cadres dirigeants": (2, 4), "Procédures collectives": (1, 3)},
         types={"contentieux": 40, "conclusions": 35},
         sectors="Industrie, Pharmaceutique, Chimie, Distribution / retail", countries="France, Suisse, Espagne",
         legal="Droit français, Droit de l'UE, Droit suisse", prefs="contentieux, rédaction", lit=3, intl=1),
    dict(name="Manon Petit", role=Role.SENIOR, age=32, years=5, specialty="Compliance",
         langs="Français C2, Anglais C2", domains={COMPL: (3, 30), PENAL: (1, 2)},
         subs={"Anticorruption (Sapin II)": (3, 15), "RGPD et IA": (3, 10), "Droit de la concurrence": (2, 6),
               "Corruption et enquêtes internes": (1, 2)},
         types={"conseil": 25, "audit": 12},
         sectors="Technologies, Investissement, BTP", legal="Droit français, Droit de l'UE",
         prefs="recherche, rédaction", trans=1, intl=1),
    dict(name="Victor Rey", role=Role.SENIOR, age=36, years=7, specialty="Private Equity",
         langs="Français C2, Anglais C2", domains={M_A: (3, 38), FISC: (2, 6), RESTR: (2, 9)},
         subs={"Fonds d'investissement": (3, 14), "Acquisitions de sociétés": (2, 10), "Due diligence": (3, 15),
               "Contrôle des investissements étrangers": (2, 5), "Opérations transfrontalières": (2, 4),
               "Prix de transfert et contrôle fiscal": (2, 4), "Financement de projets et sûretés": (2, 5),
               "Restructuration de dette": (2, 4)},
         types={"transactionnel": 30, "audit": 15},
         sectors="Capital-investissement, Énergie, Banque et finance", countries="France, Royaume-Uni, Luxembourg",
         legal="Droit français, Droit de l'UE", prefs="négociation", trans=3, intl=2),
    # ----- Collaborateurs
    dict(name="Chloé Faure", role=Role.ASSOCIATE, age=30, years=4, specialty="Corporate",
         langs="Français C2, Anglais B2", domains={CORP: (3, 22), IMMO: (2, 6), SOCIAL: (1, 2)},
         subs={"Restructurations de groupe": (2, 8), "Joint-ventures et implantation internationale": (2, 6),
               "Droit OHADA": (2, 4), "Audit contractuel": (3, 10), "Baux commerciaux": (2, 6),
               "Licenciements économiques (PSE)": (1, 2)},
         types={"transactionnel": 15, "acte": 20, "formalites": 15},
         sectors="Mines, Industrie, Distribution / retail", countries="France, Côte d'Ivoire, Sénégal",
         legal="Droit français, Droit OHADA", prefs="rédaction", trans=2, intl=1),
    dict(name="Paul Marchand", role=Role.ASSOCIATE, age=31, years=4, specialty="Pénal des affaires",
         langs="Français C2", domains={PENAL: (2, 14), COMPL: (1, 2)},
         subs={"Corruption et enquêtes internes": (2, 6), "Fraude et abus de biens sociaux": (2, 5),
               "Anticorruption (Sapin II)": (1, 2)},
         types={"contentieux": 10, "conseil": 5}, sectors="BTP", prefs="contentieux, recherche", lit=2),
    dict(name="Anaïs Robert", role=Role.ASSOCIATE, age=30, years=4, specialty="Compliance",
         langs="Français C2, Anglais C2", domains={COMPL: (2, 14), PI: (1, 2)},
         subs={"RGPD et IA": (2, 7), "Droit de la concurrence": (2, 4), "Anticorruption (Sapin II)": (2, 5),
               "Bases de données": (1, 2)},
         types={"conseil": 12, "audit": 5}, sectors="Technologies, Sidérurgie, Distribution / retail",
         legal="Droit français, Droit de l'UE", prefs="recherche, rédaction", trans=1, intl=1),
    dict(name="Maxime Laurent", role=Role.ASSOCIATE, age=29, years=3, specialty="Contentieux commercial",
         langs="Français C2", domains={CONT: (2, 16), PUBLIC: (2, 4), PI: (1, 2), SOCIAL: (1, 3)},
         subs={"Contentieux contractuel": (2, 8), "Recouvrement": (2, 10), "Rupture brutale et distribution": (1, 3),
               "Contentieux international et arbitrage": (1, 1), "Commande publique": (2, 4), "Marques": (1, 2),
               "Licenciements économiques (PSE)": (1, 1), "Cadres dirigeants": (1, 2)},
         types={"contentieux": 15, "conclusions": 12}, sectors="Industrie, BTP",
         prefs="contentieux, rédaction", lit=2),
    dict(name="Emma Rolland", role=Role.ASSOCIATE, age=30, years=4, specialty="M&A",
         langs="Français C2, Anglais C2", domains={M_A: (2, 18), FISC: (1, 2), RESTR: (1, 2)},
         subs={"Acquisitions de sociétés": (2, 7), "Fusions": (2, 4), "Opérations transfrontalières": (2, 3),
               "Contrôle des investissements étrangers": (1, 2), "Due diligence": (2, 8),
               "Prix de transfert et contrôle fiscal": (1, 1), "Réglementation bancaire": (1, 2)},
         types={"transactionnel": 12, "audit": 10}, sectors="Matériaux de construction, Technologies",
         countries="France, États-Unis", legal="Droit français, Common law", prefs="négociation, rédaction",
         trans=2, intl=1),
    # ----- Juniors
    dict(name="Lucas Henry", role=Role.JUNIOR, age=27, years=2, specialty="Corporate",
         langs="Français C2, Anglais B2", domains={CORP: (1, 5), IMMO: (1, 1)},
         subs={"Droit OHADA": (1, 2), "Audit contractuel": (1, 3), "Joint-ventures et implantation internationale": (1, 1),
               "Baux commerciaux": (1, 1)},
         types={"formalites": 6, "acte": 4}, countries="France, Maroc", legal="Droit français, Droit OHADA",
         prefs="rédaction, recherche", trans=1),
    dict(name="Alice Perrin", role=Role.JUNIOR, age=27, years=2, specialty="Compliance",
         langs="Français C2", domains={COMPL: (1, 4)},
         subs={"Anticorruption (Sapin II)": (1, 2), "RGPD et IA": (1, 2)}, types={"conseil": 4},
         prefs="recherche"),
    dict(name="Baptiste Caron", role=Role.JUNIOR, age=26, years=1, specialty="Recherche pénale",
         langs="Français C2", domains={PENAL: (1, 3)},
         subs={"Corruption et enquêtes internes": (1, 2), "Fraude et abus de biens sociaux": (1, 1)},
         types={"consultation": 5}, prefs="recherche", lit=1),
    dict(name="Inès Roux", role=Role.JUNIOR, age=27, years=2, specialty="Rédaction juridique",
         langs="Français C2", domains={CORP: (1, 3), IMMO: (1, 2), PUBLIC: (1, 1), CONT: (1, 2)},
         subs={"Audit contractuel": (1, 3), "Baux commerciaux": (1, 2), "Commande publique": (1, 1),
               "Contentieux contractuel": (1, 2)},
         types={"acte": 10, "conclusions": 3}, prefs="rédaction", lit=1, trans=1),
    dict(name="Tom Laurent", role=Role.JUNIOR, age=26, years=1, specialty="Corporate",
         langs="Français C2, Anglais C2", domains={CORP: (1, 3), M_A: (1, 2)},
         subs={"Audit contractuel": (1, 2), "Restructurations de groupe": (1, 1), "Acquisitions de sociétés": (1, 1),
               "Due diligence": (1, 2)},
         types={"audit": 3, "formalites": 2}, countries="France, Royaume-Uni", prefs="recherche, rédaction", trans=1),
    # ----- Stagiaires
    dict(name="Clara Dupont", role=Role.INTERN, age=24, years=0, specialty="Corporate", langs="Français C2, Anglais B2",
         domains={CORP: (1, 1)}, subs={"Restructurations de groupe": (1, 0), "Audit contractuel": (1, 1)},
         prefs="rédaction"),
    dict(name="Hugo Lambert", role=Role.INTERN, age=24, years=0, specialty="M&A", langs="Français C2",
         domains={M_A: (1, 1)}, subs={"Due diligence": (1, 1), "Acquisitions de sociétés": (1, 0)},
         prefs="recherche"),
    dict(name="Sarah Benhamou", role=Role.INTERN, age=24, years=0, specialty="Compliance", langs="Français C2",
         domains={COMPL: (1, 1)}, subs={"Anticorruption (Sapin II)": (1, 1), "RGPD et IA": (1, 0)},
         prefs="recherche"),
    dict(name="Adrien Petit", role=Role.INTERN, age=24, years=0, specialty="Pénal des affaires", langs="Français C2",
         domains={PENAL: (1, 1)}, subs={"Corruption et enquêtes internes": (1, 1)}, prefs="recherche, contentieux"),
    dict(name="Laura Meyer", role=Role.INTERN, age=24, years=0, specialty="Contentieux", langs="Français C2, Anglais C1",
         domains={CONT: (1, 2)},
         subs={"Contentieux contractuel": (1, 1), "Recouvrement": (1, 1), "Contentieux international et arbitrage": (1, 0),
               "Rupture brutale et distribution": (1, 0)}, prefs="contentieux, rédaction"),
    dict(name="Mehdi Cohen", role=Role.INTERN, age=24, years=0, specialty="Due Diligence", langs="Français C2",
         domains={M_A: (1, 2), COMPL: (1, 1)}, subs={"Due diligence": (1, 2), "Anticorruption (Sapin II)": (1, 1)},
         prefs="recherche"),
    dict(name="Eva Martin", role=Role.INTERN, age=24, years=0, specialty="Corporate", langs="Français C2, Anglais C2",
         domains={CORP: (1, 0), M_A: (1, 0)},
         subs={"Joint-ventures et implantation internationale": (1, 0), "Fonds d'investissement": (1, 0)},
         prefs="rédaction, recherche"),
    dict(name="Nathan Robert", role=Role.INTERN, age=24, years=0, specialty="Corporate", langs="Français C2",
         domains={CORP: (1, 0)}, subs={"Droit OHADA": (1, 0), "Restructurations de groupe": (1, 0)},
         prefs="rédaction"),
]

# --------------------------------------------------------------------------- clients
CLIENTS = {  # nom: (secteur, langue maternelle, pays)
    "Banque Occitane SA": ("Banque et finance", "Français", "France"),
    "Métallurgie Rhodanienne SA": ("Industrie", "Français", "France"),
    "Atlantica Holding": ("Industrie", "Français", "Côte d'Ivoire"),
    "Neuronis AI SAS": ("Technologies", "Français", "France"),
    "Technoplast Industries SA": ("Industrie", "Français", "France"),
    "EnerGreen Développement SAS": ("Énergie", "Français", "France"),
    "Lumière de Paris SAS": ("Luxe et cosmétique", "Français", "France"),
    "Groupe Halvard SA": ("Industrie", "Français", "France"),
    "Atlas Négoce SA": ("Négoce international", "Français", "France"),
    "Mode Évasion SAS": ("Distribution / retail", "Français", "France"),
    "Continentale Travaux SA": ("BTP", "Français", "France"),
    "Distribelle SAS": ("Distribution / retail", "Français", "France"),
    "PharmaNova SA": ("Pharmaceutique", "Français", "France"),
    "Groupe Lacour": ("BTP", "Français", "France"),
    "MinerAfrica": ("Mines", "Français", "Côte d'Ivoire"),
    "Groupe Delta SA": ("Industrie", "Français", "France"),
    "Chemtec SA": ("Chimie", "Français", "France"),
    "Conseil Stratégique Paris SAS": ("Conseil", "Français", "France"),
    "CloudSoft SA": ("Technologies", "Français", "France"),
    "Ferratech SA": ("Sidérurgie", "Français", "France"),
    "Créancière Export SA": ("Industrie", "Français", "France"),
    "Chimex Industries SA": ("Chimie", "Français", "France"),
    "Famille Morel": ("Particuliers", "Français", "Suisse"),
    "Holding Sterne SA": ("Investissement", "Français", "France"),
    "Dumont Matériaux SA": ("Matériaux de construction", "Français", "France"),
    "Lyon Composants SA": ("Industrie", "Français", "France"),
    "Innovatech Capital": ("Capital-investissement", "Français", "France"),
    "Groupe Industriel Normand SA": ("Industrie", "Français", "France"),
    "Manufacture Lorraine SAS": ("Industrie", "Français", "France"),
    "Groupe Vauban SA": ("Technologies", "Français", "France"),
    "RetailPlus SAS": ("Distribution / retail", "Français", "France"),
    "Meridian Capital Ltd": ("Investissement", "Anglais", "Royaume-Uni"),
}

CONFLICTS = [  # (personne, client, motif)
    ("Victor Rey", "Meridian Capital Ltd", "A conseillé un enchérisseur concurrent sur la même cible"),
    ("Anaïs Robert", "Neuronis AI SAS", "Lien personnel avec un dirigeant"),
    ("Maxime Laurent", "Groupe Lacour", "A travaillé pour l'attributaire du marché (BTP Occitan)"),
]

# --------------------------------------------------------------------------- dossiers
# n : n° du tableau ; priority : colonne « Rang » ; type : transactionnel / contentieux / conseil
# status : to_assign (équipe à constituer), proposing (cascade en cours) ou active (équipe en place)
# team : associés, collaborateurs, stagiaires
# tasks : (titre, collaborateur, heures, échéance en jours, statut, stagiaire, heures déjà saisies)
#   statut : accepted (à lancer), in_progress, delegation_pending, in_review, done
MATTERS = [
    dict(n=1, priority=2, name="Acquisition de NovaPay SAS par Banque Occitane", client="Banque Occitane SA",
         domain=M_A, sub="Acquisitions de sociétés", type="transactionnel", complexity=3, hours=60, due=21,
         status="active", partners=["Jean Moreau", "Pierre Richard"], lawyers=["Léa Garnier"], interns=["Hugo Lambert"],
         steps=["Due diligence réglementaire (agréments ACPR/AMF, DSP2, LCB-FT)",
                "Notification du changement de contrôle à l'ACPR au moins deux mois avant le closing",
                "Négociation du SPA et des garanties (plafond indicatif 20 % du prix)",
                "Closing conditionné à la non-opposition de l'ACPR dans les trois mois",
                "Compétence en cas de litige : Tribunal de commerce de Paris",
                "Plan d'intégration post-acquisition sur 6 à 12 mois"],
         tasks=[("Due diligence réglementaire ACPR / AMF / DSP2", "Léa Garnier", 8, 6, "in_progress", "Hugo Lambert", 3),
                ("Notification du changement de contrôle à l'ACPR", "Léa Garnier", 4, 4, "in_progress", None, 1.5),
                ("Préparer la liste de questions pour la data room", "Léa Garnier", 3, 2, "delegation_pending", "Hugo Lambert", 0),
                ("Négociation du SPA et des garanties", "Léa Garnier", 12, 15, "accepted", None, 0)]),
    dict(n=2, priority=17, name="Litige d'approvisionnement entre industriels", client="Métallurgie Rhodanienne SA",
         domain=CONT, sub="Contentieux contractuel", type="contentieux", complexity=2, hours=30, due=25,
         status="active", partners=["Nicolas Martin"], lawyers=["Maxime Laurent"], interns=[],
         steps=["Analyse du contrat d'approvisionnement et des manquements du fournisseur (retards, volumes)",
                "Chiffrage du préjudice (surcoûts d'approvisionnement de substitution, arrêts de production)",
                "Mise en demeure et tentative de règlement amiable",
                "Assignation devant le tribunal de commerce compétent en responsabilité contractuelle",
                "Gestion de l'expertise judiciaire éventuelle",
                "Suivi de la procédure jusqu'à décision ou transaction"],
         tasks=[("Analyse du contrat d'approvisionnement", "Maxime Laurent", 4, -3, "done", None, 4),
                ("Mise en demeure du fournisseur", "Maxime Laurent", 2, 3, "in_progress", None, 0.5)]),
    dict(n=3, priority=9, name="Restructuration du groupe Atlantica (France, Côte d'Ivoire, Sénégal)",
         client="Atlantica Holding", domain=CORP, sub="Droit OHADA", type="transactionnel", complexity=3, hours=50,
         due=30, legal_system="Droit OHADA", country="Côte d'Ivoire",
         status="active", partners=["Thomas Bernard", "Julien Mercier"], lawyers=["Lucas Henry"], interns=["Nathan Robert"],
         steps=["Cartographie juridique du groupe (droit français / Acte uniforme OHADA sur les sociétés commerciales)",
                "Conception du schéma (fusion-absorption en France, apport partiel d'actif pour les filiales OHADA)",
                "Rédaction des actes conformes à l'Acte uniforme OHADA (rapport du commissaire aux apports, AGE)",
                "Formalités au Registre du Commerce et du Crédit Mobilier compétent (Abidjan, Dakar)",
                "Coordination avec des correspondants locaux pour les aspects fiscaux et sociaux",
                "Information des représentants du personnel selon les règles locales",
                "Mise à jour des registres de commerce dans les trois pays"],
         tasks=[("Cartographie juridique du groupe", "Lucas Henry", 6, -2, "done", None, 6),
                ("Rédaction des actes OHADA (AGE, rapport du commissaire aux apports)", "Lucas Henry", 8, 9, "in_progress", "Nathan Robert", 2)]),
    dict(n=4, priority=19, name="Mise en conformité d'une plateforme d'IA (RGPD et AI Act)", client="Neuronis AI SAS",
         domain=COMPL, sub="RGPD et IA", type="conseil", complexity=2, hours=25, due=5,
         status="to_assign", partners=["Marie Lefèvre", "Claire Delattre"],
         steps=["Cartographie des traitements de données et des systèmes d'IA de la plateforme",
                "Qualification des systèmes au regard de l'AI Act (niveau de risque, obligations applicables)",
                "Analyse d'impact relative à la protection des données (AIPD)",
                "Mise à jour de la documentation (registre, politique de confidentialité, documentation technique)",
                "Plan de gouvernance des données et de l'IA (rôles, procédures, contrôles)",
                "Formation des équipes produit et juridique"]),
    dict(n=5, priority=6, name="PSE de Technoplast Industries (85 licenciements)", client="Technoplast Industries SA",
         domain=SOCIAL, sub="Licenciements économiques (PSE)", type="conseil", complexity=3, hours=70, due=7,
         status="to_assign", partners=["Nicolas Martin"],
         steps=["Information du CSE sur le projet de réorganisation",
                "Élaboration du PSE (reclassement interne, congé de reclassement)",
                "Négociation d'un accord collectif majoritaire ou document unilatéral homologué par la DREETS",
                "Délai de consultation du CSE de deux mois (moins de cent licenciements envisagés)",
                "Notification individuelle des licenciements après validation / homologation",
                "Prescription des contestations : douze mois",
                "Suivi des obligations de revitalisation du bassin d'emploi"]),
    dict(n=6, priority=8, name="Financement du projet éolien offshore « Côte Atlantique »",
         client="EnerGreen Développement SAS", domain=RESTR, sub="Financement de projets et sûretés",
         type="transactionnel", complexity=3, hours=80, due=18, status="to_assign",
         partners=["Julien Mercier", "Jean Moreau"],
         steps=["Structuration du financement (SPV dédié, ratio dette / fonds propres)",
                "Négociation de la convention de crédit senior avec le pool bancaire",
                "Due diligence sur les contrats du projet (EPC, PPA, concession du domaine public maritime)",
                "Mise en place des sûretés (nantissement de compte et d'actions, cession Dailly, hypothèque maritime)",
                "Vérification des autorisations administratives (autorisation environnementale, raccordement RTE)",
                "Négociation des conditions suspensives au premier tirage",
                "Suivi des covenants financiers en phase de construction"]),
    dict(n=7, priority=13, name="Contrefaçon de la marque « Lumière de Paris » en Europe",
         client="Lumière de Paris SAS", domain=PI, sub="Marques", type="contentieux", complexity=2, hours=40, due=20,
         status="to_assign", partners=["Nicolas Martin"], legal_system="Droit de l'UE",
         steps=["Cartographie des atteintes constatées par pays",
                "Action en nullité d'une marque notoire : prescription de cinq ans, sauf mauvaise foi du déposant",
                "Mise en demeure et actions de cessation",
                "Coordination des actions dans chaque juridiction concernée",
                "Constats et preuves de la contrefaçon (huissier, enquêtes)",
                "Négociation d'accords transactionnels ou suivi des décisions obtenues"]),
    dict(n=8, priority=14, name="Contrôle fiscal sur les prix de transfert du groupe Halvard", client="Groupe Halvard SA",
         domain=FISC, sub="Prix de transfert et contrôle fiscal", type="conseil", complexity=3, hours=45, due=28,
         status="active", partners=["Camille Dubois", "Jean Moreau"], lawyers=["Emma Rolland"], interns=[],
         steps=["Analyse de l'avis de vérification et du périmètre du contrôle (opérations intragroupe)",
                "Revue de la documentation prix de transfert (master file, local file)",
                "Réponse aux demandes de l'administration et préparation des entretiens",
                "Analyse de la proposition de rectification et réponse dans le délai de trente jours",
                "Saisine de la commission départementale ou recours hiérarchique",
                "Évaluation d'une procédure amiable ou d'un contentieux fiscal"],
         tasks=[("Revue de la documentation prix de transfert", "Emma Rolland", 6, 5, "in_progress", None, 2)]),
    dict(n=9, priority=12, name="Arbitrage Atlas Négoce / Maghreb Trading", client="Atlas Négoce SA",
         domain=CONT, sub="Contentieux international et arbitrage", type="contentieux", complexity=3, hours=90,
         due=26, country="Maroc", status="to_assign", partners=["Nicolas Martin", "Claire Delattre"],
         steps=["Analyse de la clause compromissoire et détermination du droit applicable",
                "Constitution du tribunal arbitral (par exemple siège à Paris sous l'égide de la CCI)",
                "Rédaction des mémoires (demande, défense, réplique)",
                "Phase probatoire (pièces, témoins, experts)", "Audience de plaidoirie",
                "Suivi de la sentence et de son exequatur en France et au Maroc"]),
    dict(n=10, priority=32, name="Renégociation des baux commerciaux de Mode Évasion (25 magasins)",
         client="Mode Évasion SAS", domain=IMMO, sub="Baux commerciaux", type="transactionnel", complexity=1,
         hours=35, due=40, status="to_assign", partners=["Thomas Bernard"],
         steps=["Analyse des baux existants et des échéances de renouvellement",
                "Congé ou demande de renouvellement au moins six mois avant l'expiration du bail",
                "Évaluation de la valeur locative pour la fixation du loyer de renouvellement",
                "Négociation avec les bailleurs (déplafonnement éventuel)",
                "Rédaction des avenants ou nouveaux baux pour chaque point de vente",
                "Contentieux éventuels de fixation de loyer devant le juge des loyers commerciaux"]),
    dict(n=11, priority=4, name="Enquête interne « Projet Ambre » (soupçons de corruption)",
         client="Continentale Travaux SA", domain=PENAL, sub="Corruption et enquêtes internes", type="conseil",
         complexity=3, hours=120, due=14, status="active", partners=["Claire Delattre", "Sarah Cohen"],
         lawyers=["Arthur Simon", "Paul Marchand", "Baptiste Caron"], interns=["Adrien Petit"],
         steps=["Cadrage de l'enquête sous privilège, désignation d'un cabinet indépendant",
                "Préservation des preuves (legal hold), collecte documentaire",
                "Entretiens avec les collaborateurs concernés",
                "Analyse de l'obligation de signalement à l'AFA et au PNF",
                "Rapport et plan de remédiation (cartographie des risques, code de conduite, formations Sapin II)",
                "Information du conseil d'administration et des commissaires aux comptes"],
         tasks=[("Legal hold et collecte documentaire", "Paul Marchand", 6, -4, "done", None, 6),
                ("Entretiens avec les collaborateurs concernés", "Arthur Simon", 12, 6, "in_progress", None, 4),
                ("Note sur l'obligation de signalement AFA / PNF", "Baptiste Caron", 4, 3, "in_review", "Adrien Petit", 3.5)]),
    dict(n=12, priority=24, name="Rupture du contrat de distribution exclusive Distribelle / HandelsPartner",
         client="Distribelle SAS", domain=CONT, sub="Rupture brutale et distribution", type="contentieux",
         complexity=2, hours=20, due=22, country="Allemagne", status="active", partners=["Nicolas Martin"],
         lawyers=["Hugo Blanc"], interns=["Laura Meyer"],
         steps=["Analyse du contrat de distribution et qualification de la rupture au regard du droit de l'UE",
                "Rupture libre sous réserve d'un préavis écrit tenant compte de la durée de la relation",
                "Évaluation du préavis raisonnable et du préjudice indemnisable",
                "Mise en demeure et tentative de négociation amiable",
                "Assignation devant le tribunal de commerce compétent en cas d'échec",
                "Suivi de la procédure jusqu'à décision ou transaction"],
         tasks=[("Évaluation du préavis et du préjudice", "Hugo Blanc", 5, 5, "in_progress", "Laura Meyer", 1.5)]),
    dict(n=13, priority=11, name="Contrefaçon du brevet pharmaceutique « Molécule X »", client="PharmaNova SA",
         domain=PI, sub="Brevets", type="contentieux", complexity=3, hours=75, due=6, status="to_assign",
         partners=["Nicolas Martin", "Pierre Richard"],
         steps=["Analyse de la validité et de la portée des revendications du brevet",
                "Saisie-contrefaçon ordonnée par le président du Tribunal judiciaire de Paris",
                "Mesures possibles : rappel, destruction ou confiscation des produits contrefaisants",
                "Opposition au brevet : délai de neuf mois après la publication au BOPI",
                "Rédaction et dépôt de l'assignation en contrefaçon",
                "Gestion de la demande reconventionnelle en nullité",
                "Négociation d'un accord transactionnel ou d'une licence"]),
    dict(n=14, priority=20, name="Contestation du marché public attribué à BTP Occitan", client="Groupe Lacour",
         domain=PUBLIC, sub="Commande publique", type="contentieux", complexity=2, hours=30, due=9,
         status="to_assign", partners=["Nicolas Martin"],
         steps=["Analyse du dossier de consultation et des motifs de rejet de l'offre",
                "Référé précontractuel avant signature, ou référé contractuel dans les six mois",
                "Pourvoi devant le Conseil d'État dans la quinzaine de la notification",
                "Requête devant le tribunal administratif territorialement compétent",
                "Audience en urgence",
                "Suivi de la décision et évaluation d'une action indemnitaire"]),
    dict(n=15, priority=16, name="Joint-venture franco-ivoirienne « MinerAfrica »", client="MinerAfrica",
         domain=CORP, sub="Joint-ventures et implantation internationale", type="transactionnel", complexity=3,
         hours=55, due=24, country="Côte d'Ivoire", legal_system="Droit OHADA",
         status="active", partners=["Thomas Bernard"], lawyers=["Chloé Faure"], interns=[],
         steps=["Négociation du term sheet et structuration de la JV",
                "Due diligence réglementaire minière (code minier ivoirien, régime OHADA)",
                "Rédaction du pacte d'actionnaires et des statuts conformes à l'Acte uniforme OHADA",
                "Obtention des autorisations et permis miniers",
                "Négociation des accords connexes (approvisionnement, gestion opérationnelle)",
                "Mise en place de la gouvernance de la JV"],
         tasks=[("Négociation du term sheet", "Chloé Faure", 6, 4, "in_progress", None, 2)]),
    dict(n=16, priority=25, name="Contestation du licenciement de M. Favier (directeur général salarié)",
         client="Groupe Delta SA", domain=SOCIAL, sub="Cadres dirigeants", type="contentieux", complexity=2,
         hours=25, due=4, status="to_assign", partners=["Nicolas Martin"],
         steps=["Analyse du contrat de travail et des circonstances du licenciement",
                "Évaluation du bien-fondé et des indemnités dues (conventionnelle, non-concurrence)",
                "Tentative de négociation d'une transaction",
                "Prescription de deux ans pour l'action portant sur l'exécution du contrat",
                "Saisine du conseil de prud'hommes en cas d'échec amiable",
                "Suivi de la procédure jusqu'à décision ou exécution de l'accord"]),
    dict(n=17, priority=26, name="Refus d'indemnisation du sinistre de l'usine Chemtec", client="Chemtec SA",
         domain=CONT, sub="Assurances", type="contentieux", complexity=2, hours=40, due=35, status="to_assign",
         partners=["Nicolas Martin"],
         steps=["Analyse du contrat d'assurance et des clauses d'exclusion invoquées",
                "Contestation du refus de garantie auprès de l'assureur",
                "Expertise contradictoire", "Prescription biennale des actions dérivant du contrat d'assurance",
                "Mise en demeure et tentative de règlement amiable",
                "Assignation devant le tribunal compétent"]),
    dict(n=18, priority=22, name="Implantation au Maroc de Conseil Stratégique Paris",
         client="Conseil Stratégique Paris SAS", domain=CORP, sub="Joint-ventures et implantation internationale",
         type="transactionnel", complexity=1, hours=20, due=30, country="Maroc", status="to_assign",
         partners=["Thomas Bernard", "Camille Dubois"],
         steps=["Choix de la structure locale (succursale ou filiale marocaine)",
                "Due diligence réglementaire sur l'activité de conseil au Maroc",
                "Statuts et formalités auprès du Centre régional d'investissement",
                "Analyse fiscale et sociale (convention fiscale France-Maroc)",
                "Contrats locaux (bail commercial, contrats de travail, prestations)",
                "Coordination avec un correspondant marocain"]),
    dict(n=19, priority=29, name="Licence SaaS internationale de CloudSoft", client="CloudSoft SA",
         domain=PI, sub="Contrats IT et SaaS", type="transactionnel", complexity=2, hours=30, due=33,
         status="to_assign", partners=["Marie Lefèvre", "Pierre Richard"],
         steps=["Analyse du modèle économique (licence perpétuelle ou SaaS par abonnement)",
                "Négociation des conditions de licence (périmètre, durée, tarification)",
                "Clauses de propriété intellectuelle et de protection des données (RGPD)",
                "Niveaux de service (SLA) et clauses de responsabilité",
                "Conformité export et réglementaire internationale",
                "Finalisation et signature du contrat-cadre"]),
    dict(n=20, priority=3, name="Enquête de la Commission européenne : entente Ferratech / Siderex / Acerix",
         client="Ferratech SA", domain=COMPL, sub="Droit de la concurrence", type="conseil", complexity=3,
         hours=100, due=12, legal_system="Droit de l'UE", status="active", partners=["Marie Lefèvre"],
         lawyers=["Anaïs Robert", "Alice Perrin"], interns=[],
         steps=["Réception de la communication des griefs, computation du délai de réponse",
                "Accès au dossier d'instruction",
                "Réponse écrite et demande d'audition orale",
                "Évaluation d'un programme de clémence ou d'une transaction",
                "Recours possible devant le Tribunal de l'Union européenne (deux mois)",
                "Provisionnement du risque d'amende (jusqu'à 10 % du chiffre d'affaires mondial)"],
         tasks=[("Analyse de la communication des griefs", "Anaïs Robert", 10, 7, "in_progress", None, 3),
                ("Accès au dossier d'instruction", "Alice Perrin", 3, -1, "done", None, 3)]),
    dict(n=21, priority=30, name="Recouvrement d'une créance de 2,5 M€ sur Débitrice Industries",
         client="Créancière Export SA", domain=CONT, sub="Recouvrement", type="contentieux", complexity=1,
         hours=20, due=15, status="active", partners=["Nicolas Martin"], lawyers=["Maxime Laurent"],
         interns=["Laura Meyer"],
         steps=["Analyse de la créance et des justificatifs (factures, bons de commande, relances)",
                "Mise en demeure par lettre recommandée avec accusé de réception",
                "Requête en injonction de payer, ou assignation au fond si la créance est contestée",
                "Opposition possible dans le mois de la signification",
                "Suivi de la procédure en cas d'opposition",
                "Mesures d'exécution forcée (saisie-attribution, saisie conservatoire)"],
         tasks=[("Requête en injonction de payer", "Maxime Laurent", 3, 4, "delegation_pending", "Laura Meyer", 0)]),
    dict(n=22, priority=10, name="Restructuration de la dette de Chimex Industries (3 banques)",
         client="Chimex Industries SA", domain=RESTR, sub="Restructuration de dette", type="transactionnel",
         complexity=3, hours=65, due=20, status="active", partners=["Julien Mercier"], lawyers=["Victor Rey"],
         interns=[],
         steps=["Diagnostic financier indépendant",
                "Conciliation devant le président du tribunal de commerce (cinq mois maximum)",
                "Protocole de conciliation (rééchelonnement, abandons partiels, conversion en quasi-fonds propres)",
                "Homologation judiciaire du protocole",
                "Avenants et nouvelles sûretés", "Suivi de l'exécution et reporting aux banques"],
         tasks=[("Préparation de la procédure de conciliation", "Victor Rey", 8, 6, "in_progress", None, 3)]),
    dict(n=23, priority=15, name="Litige franco-suisse sur la propriété de la Villa Les Cèdres", client="Famille Morel",
         domain=CONT, sub="Contentieux international et arbitrage", type="contentieux", complexity=2, hours=45,
         due=27, country="Suisse", legal_system="Droit suisse", status="to_assign",
         partners=["Nicolas Martin"],
         steps=["Loi applicable et juridiction compétente (loi du lieu de situation de l'immeuble)",
                "Analyse des titres de propriété et de la chaîne contractuelle",
                "Rédaction des écritures (assignation, conclusions)", "Gestion de l'expertise judiciaire",
                "Coordination avec un conseil suisse", "Exécution transfrontalière de la décision"]),
    dict(n=24, priority=23, name="Audit anticorruption avant l'acquisition d'Infratech Services",
         client="Holding Sterne SA", domain=COMPL, sub="Anticorruption (Sapin II)", type="conseil", complexity=2,
         hours=35, due=10, status="active", partners=["Marie Lefèvre", "Claire Delattre"], lawyers=["Manon Petit"],
         interns=["Sarah Benhamou", "Mehdi Cohen"],
         steps=["Périmètre et méthodologie de l'audit", "Revue des procédures de conformité de la cible",
                "Entretiens avec les équipes clés et revue documentaire",
                "Identification des zones de risque et red flags (agents publics, intermédiaires)",
                "Rapport d'audit et recommandations",
                "Intégration des conclusions dans la négociation (garanties, ajustement de prix)"],
         tasks=[("Revue des procédures de conformité de la cible", "Manon Petit", 6, 4, "in_progress", "Mehdi Cohen", 2),
                ("Cartographie des red flags", "Manon Petit", 4, -1, "done", "Sarah Benhamou", 4),
                ("Entretiens avec les équipes clés", "Manon Petit", 6, 8, "accepted", None, 0)]),
    dict(n=25, priority=18, name="Fusion de Dumont Matériaux et Rocher Bâtiment", client="Dumont Matériaux SA",
         domain=M_A, sub="Fusions", type="transactionnel", complexity=2, hours=55, due=23, status="active",
         partners=["Pierre Richard", "Thomas Bernard"], lawyers=["Emma Rolland"], interns=["Clara Dupont"],
         steps=["Due diligence réciproque des deux sociétés",
                "Traité de fusion et désignation du commissaire à la fusion",
                "Seuil de notification à l'Autorité de la concurrence",
                "Information-consultation des CSE des deux sociétés",
                "Formalités de publicité légale et d'enregistrement au greffe",
                "Intégration post-fusion (systèmes, personnel, marque)"],
         tasks=[("Due diligence réciproque", "Emma Rolland", 8, 7, "in_progress", "Clara Dupont", 2.5),
                ("Projet de traité de fusion", "Emma Rolland", 6, 12, "accepted", None, 0)]),
    dict(n=26, priority=21, name="Litige Lyon Composants / Barcelona Supply", client="Lyon Composants SA",
         domain=CONT, sub="Contentieux international et arbitrage", type="contentieux", complexity=2, hours=40,
         due=19, country="Espagne", legal_system="Droit de l'UE", status="to_assign",
         partners=["Nicolas Martin", "Thomas Bernard"],
         steps=["Juridiction compétente selon le règlement Bruxelles I bis",
                "Loi applicable au contrat (règlement Rome I)",
                "Écritures et procédure devant le tribunal de commerce compétent",
                "Coordination avec un correspondant espagnol",
                "Exceptions de procédure (compétence, litispendance)",
                "Exécution de la décision dans l'autre État membre"]),
    dict(n=27, priority=28, name="Création du fonds Innovatech Capital FPCI", client="Innovatech Capital",
         domain=M_A, sub="Fonds d'investissement", type="transactionnel", complexity=2, hours=50, due=26,
         status="active", partners=["Camille Dubois"], lawyers=["Victor Rey"], interns=["Eva Martin"],
         steps=["Structuration juridique et fiscale du fonds (FPCI, société de gestion agréée AMF)",
                "Règlement du fonds et documentation réglementaire",
                "Pacte d'actionnaires type avec les sociétés cibles", "Agrément AMF de la société de gestion",
                "Gouvernance et reporting investisseurs", "Accompagnement des premiers investissements"],
         tasks=[("Rédaction du règlement du fonds", "Victor Rey", 10, -2, "done", None, 10),
                ("Dossier d'agrément AMF", "Victor Rey", 6, 8, "in_progress", "Eva Martin", 1.5)]),
    dict(n=28, priority=31, name="Audit de 150 contrats fournisseurs du Groupe Industriel Normand",
         client="Groupe Industriel Normand SA", domain=CORP, sub="Audit contractuel", type="conseil", complexity=1,
         hours=45, due=28, status="active", partners=["Julien Mercier"], lawyers=["Inès Roux", "Tom Laurent"],
         interns=[],
         steps=["Grille d'analyse contractuelle et critères de risque",
                "Revue systématique des contrats (durée, résiliation, changement de contrôle, pénalités)",
                "Identification des contrats à risque pour la restructuration",
                "Rapport de synthèse par catégorie de risque",
                "Recommandations de renégociation ou de résiliation", "Suivi des actions correctives"],
         tasks=[("Grille d'analyse contractuelle", "Tom Laurent", 3, -2, "done", None, 3),
                ("Revue des contrats (lot 1 : 50 contrats)", "Inès Roux", 12, 10, "in_progress", None, 4)]),
    dict(n=29, priority=5, name="Redressement judiciaire de Manufacture Lorraine (40 salariés)",
         client="Manufacture Lorraine SAS", domain=RESTR, sub="Procédures collectives", type="contentieux",
         complexity=2, hours=25, due=8, status="active", partners=["Julien Mercier", "Nicolas Martin"],
         lawyers=["Hugo Blanc"], interns=[],
         steps=["Constat de la cessation des paiements",
                "Déclaration au greffe dans les 45 jours, sauf conciliation demandée dans ce délai",
                "Requête en redressement judiciaire",
                "Désignation d'un administrateur et d'un mandataire judiciaires",
                "Réunion du CSE dans les dix jours du jugement d'ouverture",
                "Période d'observation (six mois renouvelables)",
                "Recherche d'un plan de continuation ou d'un repreneur"],
         tasks=[("Requête en redressement judiciaire", "Hugo Blanc", 5, 3, "in_progress", None, 2)]),
    dict(n=30, priority=7, name="Acquisition d'AmeriTech Solutions Inc. par Groupe Vauban", client="Groupe Vauban SA",
         domain=M_A, sub="Opérations transfrontalières", type="transactionnel", complexity=3, hours=90, due=16,
         country="États-Unis", legal_system="Common law", required_language="Anglais",
         status="proposing", partners=["Pierre Richard", "Jean Moreau"],
         proposals=[("Victor Rey", "refused"), ("Léa Garnier", "pending"), ("Emma Rolland", "queued")],
         steps=["Due diligence multi-juridictionnelle (droit français / droit américain)",
                "Analyse de l'éligibilité CFIUS",
                "Négociation du purchase agreement selon les standards américains",
                "Structuration fiscale transfrontalière",
                "Coordination avec les conseils locaux américains",
                "Closing et plan d'intégration post-acquisition"]),
    dict(n=31, priority=27, name="Utilisation non autorisée de la base de données clients de RetailPlus",
         client="RetailPlus SAS", domain=PI, sub="Bases de données", type="contentieux", complexity=2, hours=35,
         due=21, status="active", partners=["Marie Lefèvre", "Nicolas Martin"], lawyers=["Anaïs Robert"], interns=[],
         steps=["Titularité des droits sur la base (protection sui generis du producteur)",
                "Violations au regard du RGPD et de la concurrence déloyale (parasitisme)",
                "Mise en demeure de cessation d'utilisation",
                "Assignation (concurrence déloyale et/ou RGPD)",
                "Évaluation du préjudice et opportunité d'un référé",
                "Suivi de la procédure et de l'exécution"],
         tasks=[("Mise en demeure de cessation", "Anaïs Robert", 2, -3, "done", None, 2),
                ("Assignation (concurrence déloyale / RGPD)", "Anaïs Robert", 8, 12, "accepted", None, 0)]),
    dict(n=32, priority=1, name="Acquisition d'Energie Stratégique Française par Meridian Capital",
         client="Meridian Capital Ltd", domain=M_A, sub="Contrôle des investissements étrangers",
         type="transactionnel", complexity=3, hours=85, due=6, required_language="Anglais",
         status="to_assign", partners=["Jean Moreau", "Camille Dubois"],
         steps=["Éligibilité au contrôle des investissements étrangers (secteur de l'énergie, autorisation préalable)",
                "Due diligence juridique, financière et réglementaire de la cible",
                "Demande d'autorisation IEF auprès de la Direction générale du Trésor (30 jours ouvrés, +45 jours "
                "en cas d'examen approfondi)",
                "Négociation du SPA et des garanties d'actif et de passif",
                "Structuration de l'opération (holding d'acquisition, financement)",
                "Closing conditionné à l'autorisation IEF et formalités post-acquisition"]),
]


# --------------------------------------------------------------------------- renforts (profils fictifs ajoutés)
# Pour que chaque dossier ait toujours au moins 5 collaborateurs éligibles, le cabinet compte des collaborateurs
# supplémentaires, organisés par groupes de compétences. Chacun travaille déjà sur un dossier en cours.

def _profile(name, role, age, years, specialty, langs, domains, sectors, prefs, lit, trans, intl,
             countries="France", legal="Droit français"):
    """Profil complet : toutes les sous-spécialités d'un domaine au niveau du domaine."""
    cases = {3: 20, 2: 8, 1: 2}
    return dict(name=name, role=role, age=age, years=years, specialty=specialty, langs=langs,
                domains={d: (lvl, cases[lvl] * 2) for d, lvl in domains.items()},
                subs={s: (lvl, cases[lvl]) for d, lvl in domains.items() for s in DOMAINS[d]},
                types={"transactionnel": 10 * trans, "contentieux": 10 * lit, "conseil": 8},
                sectors=sectors, countries=countries, legal=legal, prefs=prefs, lit=lit, trans=trans, intl=intl)


S, C = Role.SENIOR, Role.ASSOCIATE
REINFORCEMENTS = [  # (profil, n° du dossier en cours dont il fait partie)
    # M&A, private equity et fiscal
    (_profile("Louis Fontaine", S, 36, 7, "M&A / Fiscal", "Français C2, Anglais C2", {M_A: 3, FISC: 2},
              "Énergie, Banque et finance", "négociation", 1, 3, 2, "France, Royaume-Uni, États-Unis",
              "Droit français, Common law"), 1),
    (_profile("Juliette Marchetti", S, 35, 6, "Private Equity", "Français C2, Anglais C2, Italien C1",
              {M_A: 3, FISC: 2}, "Capital-investissement, Technologies", "négociation, rédaction", 1, 3, 2,
              "France, Italie, Luxembourg", "Droit français, Droit de l'UE"), 27),
    (_profile("Antoine Bérard", C, 31, 4, "M&A", "Français C2, Anglais C1", {M_A: 2, FISC: 1},
              "Industrie, Matériaux de construction", "rédaction", 0, 2, 1), 25),
    (_profile("Margaux Lenoir", C, 30, 4, "Fiscalité des opérations", "Français C2, Anglais C2", {M_A: 2, FISC: 3},
              "Industrie, Banque et finance", "recherche, rédaction", 1, 2, 1), 8),
    (_profile("Samuel Haddad", C, 32, 5, "M&A Tech", "Français C2, Anglais C2, Arabe C1", {M_A: 2, FISC: 1},
              "Technologies, Capital-investissement", "négociation", 0, 2, 2, "France, États-Unis, Maroc",
              "Droit français, Common law"), 1),
    (_profile("Paul-Henri Dumas", S, 39, 9, "M&A international", "Français C2, Anglais C2, Allemand B2",
              {M_A: 3, FISC: 2}, "Énergie, Industrie", "négociation", 1, 3, 2, "France, Allemagne, Royaume-Uni",
              "Droit français, Droit de l'UE, Common law"), 1),
    # Corporate et restructuring
    (_profile("Céline Vasseur", S, 37, 8, "Corporate / OHADA", "Français C2, Anglais B2",
              {CORP: 3, RESTR: 2}, "Mines, Industrie", "rédaction, négociation", 1, 3, 2,
              "France, Côte d'Ivoire, Sénégal", "Droit français, Droit OHADA"), 3),
    (_profile("Romain Gauthier", S, 38, 8, "Restructuring", "Français C2, Anglais C1", {CORP: 2, RESTR: 3},
              "Industrie, Chimie, Énergie", "négociation", 2, 3, 1), 22),
    (_profile("Pauline Colin", C, 31, 4, "Corporate", "Français C2, Anglais B2", {CORP: 2, RESTR: 2},
              "Mines, Conseil", "rédaction", 0, 2, 1, "France, Côte d'Ivoire, Maroc", "Droit français, Droit OHADA"), 15),
    (_profile("Yann Le Goff", C, 32, 5, "Entreprises en difficulté", "Français C2, Anglais B2", {CORP: 2, RESTR: 2},
              "Industrie", "contentieux, négociation", 2, 2, 0), 29),
    (_profile("Nora Belkacem", C, 30, 3, "Corporate", "Français C2, Arabe C2, Anglais B2", {CORP: 2, RESTR: 2},
              "Industrie, Conseil", "rédaction, recherche", 0, 2, 1, "France, Maroc", "Droit français, Droit OHADA"), 28),
    (_profile("Arnaud Lefort", C, 33, 5, "Financement de projets", "Français C2, Anglais C1", {CORP: 2, RESTR: 2},
              "Énergie, Banque et finance", "négociation", 0, 3, 1, "France, Royaume-Uni"), 28),
    # Pénal des affaires et compliance
    (_profile("Isabelle Morin", S, 38, 8, "Pénal des affaires / Compliance", "Français C2, Anglais C1",
              {PENAL: 3, COMPL: 2}, "BTP, Énergie", "contentieux, recherche", 3, 1, 1), 11),
    (_profile("Karim Bensaïd", S, 37, 7, "Compliance anticorruption", "Français C2, Anglais C2, Arabe C1",
              {PENAL: 2, COMPL: 3}, "Investissement, BTP", "recherche, négociation", 1, 1, 2,
              "France, Maroc", "Droit français, Droit de l'UE"), 24),
    (_profile("Elise Carpentier", C, 31, 4, "Droit de la concurrence", "Français C2, Anglais C2", {PENAL: 2, COMPL: 2},
              "Sidérurgie, Industrie", "recherche, rédaction", 1, 1, 1, "France", "Droit français, Droit de l'UE"), 20),
    (_profile("Thibault Leclerc", C, 30, 4, "Données personnelles", "Français C2, Anglais C1", {PENAL: 2, COMPL: 2},
              "Technologies, Distribution / retail", "recherche", 1, 1, 1, "France", "Droit français, Droit de l'UE"), 31),
    (_profile("Amandine Roche", C, 32, 5, "Compliance", "Français C2, Anglais B2", {PENAL: 2, COMPL: 2},
              "BTP, Investissement", "rédaction, recherche", 1, 1, 0), 24),
    (_profile("Victoire Hamel", C, 29, 3, "Pénal des affaires", "Français C2, Anglais B2", {PENAL: 2, COMPL: 2},
              "Sidérurgie", "contentieux", 2, 0, 0, "France", "Droit français, Droit de l'UE"), 20),
    # Contentieux des affaires et droit social
    (_profile("Mathieu Perrot", S, 37, 8, "Contentieux / Arbitrage", "Français C2, Anglais C2, Espagnol C1",
              {CONT: 3, SOCIAL: 2}, "Distribution / retail, Industrie", "contentieux", 3, 1, 2,
              "France, Espagne, Suisse, Maroc", "Droit français, Droit de l'UE, Droit suisse"), 12),
    (_profile("Sophie Gaillard", S, 36, 7, "Contentieux social et commercial", "Français C2, Anglais C1",
              {CONT: 3, SOCIAL: 3}, "Industrie, Agroalimentaire", "contentieux, rédaction", 3, 1, 1), 2),
    (_profile("Damien Royer", C, 31, 4, "Contentieux commercial", "Français C2, Anglais B2", {CONT: 2, SOCIAL: 2},
              "Industrie", "contentieux", 2, 0, 0), 21),
    (_profile("Leïla Mansouri", C, 30, 4, "Contentieux international", "Français C2, Anglais C2, Arabe C2",
              {CONT: 2, SOCIAL: 2}, "Négoce international, Distribution / retail", "contentieux, recherche", 2, 1, 2,
              "France, Maroc, Espagne", "Droit français, Droit de l'UE"), 12),
    (_profile("Bastien Fabre", C, 32, 5, "Contentieux et assurances", "Français C2, Anglais B2", {CONT: 2, SOCIAL: 2},
              "Chimie, Industrie", "contentieux", 2, 0, 1), 29),
    (_profile("Grégoire Vidal", C, 29, 3, "Contentieux social", "Français C2, Anglais B2", {CONT: 2, SOCIAL: 2},
              "Agroalimentaire, Industrie", "contentieux, rédaction", 2, 0, 0), 21),
    # Propriété intellectuelle et numérique
    (_profile("Hélène Barbier", S, 38, 9, "Propriété intellectuelle", "Français C2, Anglais C2", {PI: 3},
              "Pharmaceutique, Luxe et cosmétique", "contentieux, rédaction", 3, 1, 2,
              "France, Allemagne, Italie", "Droit français, Droit de l'UE"), 31),
    (_profile("Quentin Masson", S, 36, 7, "IT / Données", "Français C2, Anglais C2", {PI: 3},
              "Technologies, Banque et finance", "négociation, rédaction", 1, 3, 2, "France, États-Unis",
              "Droit français, Droit de l'UE"), 1),
    (_profile("Clémence Duval", C, 30, 4, "Marques", "Français C2, Anglais C1", {PI: 2},
              "Luxe et cosmétique, Distribution / retail", "recherche, rédaction", 1, 1, 1), 25),
    (_profile("Florian Picard", C, 31, 4, "Brevets", "Français C2, Anglais C2, Allemand B2", {PI: 2},
              "Pharmaceutique, Industrie", "contentieux, recherche", 2, 0, 1, "France, Allemagne",
              "Droit français, Droit de l'UE"), 27),
    (_profile("Jade Lemaire", C, 29, 3, "Contrats IT", "Français C2, Anglais C2", {PI: 2},
              "Technologies", "négociation, rédaction", 0, 2, 1), 2),
    # Droit public des affaires et immobilier
    (_profile("Olivier Brun", S, 39, 9, "Droit public / Immobilier", "Français C2, Anglais B2", {PUBLIC: 3, IMMO: 3},
              "BTP, Distribution / retail", "contentieux, négociation", 2, 2, 0), 28),
    (_profile("Lucie Fournier", C, 31, 4, "Commande publique", "Français C2, Anglais B2", {PUBLIC: 2, IMMO: 2},
              "BTP", "contentieux, rédaction", 2, 1, 0), 2),
    (_profile("Gabriel Moulin", C, 30, 4, "Baux commerciaux", "Français C2, Anglais B2", {PUBLIC: 2, IMMO: 2},
              "Distribution / retail", "négociation, rédaction", 1, 2, 0), 21),
    (_profile("Agathe Renaud", C, 32, 5, "Immobilier", "Français C2, Anglais C1", {PUBLIC: 2, IMMO: 2},
              "Immobilier, Distribution / retail", "rédaction", 1, 2, 0), 22),
]

PEOPLE += [profile for profile, _ in REINFORCEMENTS]
for _profile_data, _n in REINFORCEMENTS:
    next(m for m in MATTERS if m["n"] == _n)["lawyers"].append(_profile_data["name"])

MIN_ELIGIBLE = 5  # chaque dossier doit toujours avoir au moins 5 collaborateurs éligibles
